BIN = hello_world

# SDK_DIR = ../mcu-vendor         # Target-specific library
# INC = -I$(SDK_DIR)/inc
# SRC_ASM = $(SDK_DIR)/src/startup.S
# SCR_C = $(SDK_DIR)/src/system.c
SRC_LD = link.ld

ARCHFLAGS = -mcpu=cortex-m0plus
FPFLAGS = -mfloat-abi=soft

include config.mk
include rules.mk
